### ISSUE TITLE
'Symbol not found' error on homebrewed modeller (macOS)

### ISSUE THREAD

**Issue by YoshitakaMo** [salilab/homebrew-salilab#1]
When I installed MODELLER program by using Homebrew on macOS 10.14.3, `mod9.21` doesn't work with a following message.
```
$ mod9.21 align.py
Traceback (most recent call last):
  File "align.py", line 5, in <module>
    from modeller.automodel import *    # Load the automodel class
  File "/usr/local/Cellar/modeller/9.21_1/modlib/modeller/automodel/__init__.py", line 10, in <module>
    from modeller.automodel.automodel import automodel
  File "/usr/local/Cellar/modeller/9.21_1/modlib/modeller/automodel/automodel.py", line 18, in <module>
    import io
  File "/usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
```

I found that this issue is caused by a mismatch of dynamic libraries:
```
$ otool -L /usr/local/Cellar/modeller/9.21_1/modbin/mod9.21_mac10v4
/usr/local/Cellar/modeller/9.21_1/modbin/mod9.21_mac10v4:
        /usr/local/Cellar/modeller/9.21_1/lib/libmodeller.11.dylib (compatibility version 0.0.0, current version 11.0.0)
        /usr/local/opt/hdf5@1.8.20/lib/libhdf5.10.dylib (compatibility version 14.0.0, current version 14.1.0)
        /usr/local/opt/hdf5@1.8.20/lib/libhdf5_hl.10.dylib (compatibility version 13.0.0, current version 13.1.0)
        /usr/local/Cellar/modeller/9.21_1/lib/libsaxs.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/local/opt/glib/lib/libglib-2.0.0.dylib (compatibility version 4601.0.0, current version 4601.2.0)
        /usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.5.0)
        /System/Library/Frameworks/Python.framework/Versions/2.6/Python (compatibility version 2.6.0, current version 2.6.1)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 125.2.11)
```

In the homebrewed MODELLER, `mod9.21` (or `mod9.21_mac10v4`) will depend on homebrewed python instead of system-native python. Thus, I modified the depending libraries like this

```
$ install_name_tool -change "/System/Library/Frameworks/Python.framework/Versions/2.6/Python" /usr/local/opt/python@2/Frameworks/Python.framework/Python /usr/local/Cellar/modeller/9.21_1/modbin/mod9.21_mac10v4

$ otool -L /usr/local/Cellar/modeller/9.21_1/modbin/mod9.21_mac10v4/usr/local/Cellar/modeller/9.21_1/modbin/mod9.21_mac10v4:
        /usr/local/Cellar/modeller/9.21_1/lib/libmodeller.11.dylib (compatibility version 0.0.0, current version 11.0.0)
        /usr/local/opt/hdf5@1.8.20/lib/libhdf5.10.dylib (compatibility version 14.0.0, current version 14.1.0)
        /usr/local/opt/hdf5@1.8.20/lib/libhdf5_hl.10.dylib (compatibility version 13.0.0, current version 13.1.0)
        /usr/local/Cellar/modeller/9.21_1/lib/libsaxs.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/local/opt/glib/lib/libglib-2.0.0.dylib (compatibility version 4601.0.0, current version 4601.2.0)
        /usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.5.0)
        /usr/local/opt/python@2/Frameworks/Python.framework/Python (compatibility version 2.6.0, current version 2.6.1)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 125.2.11)
```
After this, `mod9.21` worked successfully.

I hope this solution will be included in the Homebrew Formula of `modeller.rb`.

**Comment by benmwebb** [comment]
`mod9.21` is included for compatibility with very old Modeller scripts. You should be really be running your scripts like any other Python script, with `python align.py` or `python3 align.py`.

That being said, `mod9.21` is supposed to work. It is supposed to use Apple's Python though, not Homebrew's, but a path somewhere is incorrect and it's getting confused. I'll take a look.
